### ISSUE TITLE
Writing values to database

### ISSUE THREAD

**Issue by sfadschm** [tattersoftware/codeigniter4-settings#20]
I am wondering if it is possible to edit `global` settings, so to say `protected = 1` settings.
Apparently, it is not, as the `set` function only updates the session if  it finds 'protected == true'.

However, this comment states, that data would be written to the database, but the `setSession` function does not do so:
https://github.com/tattersoftware/codeigniter4-settings/blob/561628aa6e481f144acfcf92185871e4d2f8b3cc/src/Settings.php#L173-L174

This way, the example from the ReadMe does not work as `latestRelease` is protected:
`$settings->latestRelease = $newVersion;`

Am I missing out on something or can we only edit globals via the model?

BTW: Took me some time to realize that `scope` is no longer a real database field 😆 
Why is it still in the migrations?

**Comment by MGatner** [comment]
> Am I missing out on something or can we only edit globals via the model?

This is correct. Maybe Is should split these things out into different classes or something, because this isn't the first hint of confusion! Global settings (`protected = 1`) are not allowed overrides. That comment you pointed out is wrong (old) and I will update it.

Changing globals should be super easy though:
```php
model('SettingModel')->where('name', $name)->update(['content' => $content);
```

If there's demand for a shorthand to this I can add one (or you can!) but that's all it amounts to.

**Comment by sfadschm** [comment]
I think in principle, this is fine.
If anyone wants to edit globals, they can use the model (after thinking it over, thats what I will do, too).
Maybe it would be useful to have a `edit` command for spark such that admins can edit globals from the cli easily.
What about the `latestRelease` example? I think this does not work as intended. And setting the latest release version only for the session does not seem to helpful 😄 
Maybe this can be removed and a hint added that globals can only be created/added via the CLI.

**Comment by MGatner** [comment]
Good point, the `latestRelease` example is handled incorrectly in the docs. Will fix.
