### ISSUE TITLE
Authentication Optional

### ISSUE THREAD

**Issue by MGatner** [tattersoftware/codeigniter4-settings#24]
Find a way to split functionality out so that global templates can be used with Settings without requiring the authentication implementation. Might need to consider making these separate libraries.

**Comment by sfadschm** [comment]
Is there some kind of authentication still included in the current version? If so, I can't find it 😄

**Comment by MGatner** [comment]
It is optional in the library (`if function_exists('user_id')`) but **composer.json** requires an authentication implementation: https://github.com/tattersoftware/codeigniter4-settings/blob/b620309d1564a1d398f5123be0eeff03257aef00/composer.json#L21-L23

This makes it awkward for libraries that would want to use the global templating without caring abut user overrides, since they will still have to include an authentication library. Yet another reason why it might make sense to split out these features.

**Comment by sfadschm** [comment]
Ah alright. Missed that because I had Myth\Auth installed before adding settings, so it never complained.
Makes sense then 👍
