### ISSUE TITLE
Bug: Cache system not working

### ISSUE THREAD

**Issue by hunter-and1** [tattersoftware/codeigniter4-settings#3]
cache system not working

**Comment by MGatner** [comment]
Could you elaborate on what's wrong? Is this different than #2?

**Comment by hunter-and1** [comment]
i fixed change all : to - seprator for windows & error code in line #125 in file Settings u have to use local function 
`cache("settings-templates-{$name}", $setting);`
to
`$this->cache("settings-templates-{$name}", $setting);`

**Comment by MGatner** [comment]
Reopening so I remember to take a look.
