### ISSUE TITLE
Bug : function getUser in settings.php

### ISSUE THREAD

**Issue by hunter-and1** [tattersoftware/codeigniter4-settings#5]
builder in getUser function return table in settings not settings_users

**Comment by hunter-and1** [comment]
i fixed
![image](https://user-images.githubusercontent.com/15271465/106778852-b11ace80-6646-11eb-935b-053802d73d49.png)

**Comment by MGatner** [comment]
What version of CodeIgniter are you using? `Model::builder` returns a new builder for the specified table, and is preferable here in case the Settings Model is part of a different database connection.

https://github.com/codeigniter4/CodeIgniter4/blob/3f9470741ebc09c5ea43adb1d9cf2b5b37d49414/system/Model.php#L573-L581

**Comment by hunter-and1** [comment]
i use 4.0.4

**Comment by hunter-and1** [comment]
i update to vesion 4.1.1 it working good ;)

**Comment by MGatner** [comment]
Try the `develop` branch or one of the recent releases. There have been lots of changes to Model including [this bug](https://github.com/codeigniter4/CodeIgniter4/pull/3794)

**Comment by MGatner** [comment]
Whoops looks like we crossed paths! Glad you got it fixed :)
