### ISSUE TITLE
Trying to get property of non-object 

### ISSUE THREAD

**Issue by perspolise** [tattersoftware/codeigniter4-settings#7]
after move my code to real server I see this error: 

```

ErrorException

Trying to get property 'siteName' of non-object 

```

Error Log is:

```

CRITICAL - 2021-02-14 13:15:06 --> Trying to get property 'siteName' of non-object
#0 /home/serv/public_html/app/Controllers/Home.php(44): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', '/home/serv/...', 44, Array)
#1 /home/serv/public_html/system/CodeIgniter.php(920): App\Controllers\Home->index()
#2 /home/serv/public_html/system/CodeIgniter.php(406): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 /home/serv/public_html/system/CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /home/serv/public_html/public/index.php(45): CodeIgniter\CodeIgniter->run()

```

how do can I fix this error?

**Comment by MGatner** [comment]
You would need to share the relevant code, but this sounds unrelated to Settings. Did you remember to run your migrations and seeders when you moved servers?

**Comment by perspolise** [comment]
@MGatner I import my database using phpmyadmin. I check my database:


![eee](https://user-images.githubusercontent.com/19752074/107879673-8145b380-6eef-11eb-8cd7-7db3b97618ab.jpg)

**Comment by MGatner** [comment]
> Trying to get property 'siteName' of non-object

It isn't finding Settings. Probably if you add `dd($settings);` right before that you will see that it is `null`. Make sure you have run Composer install/update and the package is properly included. 

If you still have issues please raise a support question on the CodeIgniter Addins forum. You can PM me there if I don't notice it right away.
